10 retry after header
GTech1256/go-musthave-diploma-tpl pull request #9
Opened 2023-12-14 17:55 UTC by GTech1256

2023-12-15 13:11 UTC, edylcrm requested changes

2023-12-15 13:11 UTC, edylcrm commented on cmd/gophermart/main.go
> +	cfgMarshal, err := json.MarshalIndent(&cfg, "", "   ")
[LINT] Зачем это здесь?

2023-12-15 13:11 UTC, edylcrm commented on internal/client/accrual/http/client/http.go
> +	time.Sleep(time.Second)
[BLOCKER] А зачем здесь sleep?

2023-12-15 13:11 UTC, edylcrm commented on internal/composition/user/user.go
> +	handler1 := userHandler.NewHandler(h.logger, h.service)
[LINT] а по другому написать нельзя? С 1,2,3 выглядит так себе

2023-12-15 13:11 UTC, edylcrm commented on internal/db/sql/sql.go
> +	return retry.MakeRetry(func() error {
[LINK] а точно нужен retry при проверке работоспособности db?

2023-12-15 14:33 UTC, GTech1256 commented on cmd/gophermart/main.go
> +	cfgMarshal, err := json.MarshalIndent(&cfg, "", "   ")
Помогает понять с какими переменными окружения запускается приложение, чтобы не было черной коробочкой для внешнешнего анализа при плохой работы сервиса

2023-12-15 14:38 UTC, GTech1256 commented on internal/db/sql/sql.go
> +	return retry.MakeRetry(func() error {
На мой взгляд лучше с ним, чем без него
Если БД не доступна, то сервис не запуститься, а так будет шанс, что БД оживет и все запустится

2023-12-15 14:39 UTC, GTech1256 commented on internal/client/accrual/http/client/http.go
> +	time.Sleep(time.Second)
В будущем можно было бы легко оптимизировать скорость сервиса 😄 
Если серьезно, то копипаст остался с учебного проекта
Убрал
[1b5aa3b](https://github.com/GTech1256/go-musthave-diploma-tpl/pull/9/commits/1b5aa3b988ee83226d4f3afe68cc10070a43535a)

2023-12-15 14:39 UTC, GTech1256 commented on internal/composition/user/user.go
> +	handler1 := userHandler.NewHandler(h.logger, h.service)
Переименовал [c28f836](https://github.com/GTech1256/go-musthave-diploma-tpl/pull/9/commits/c28f83681974623b8842eca576bb6207c5253e07)

2023-12-18 08:49 UTC, edylcrm commented on cmd/gophermart/main.go
> +	cfgMarshal, err := json.MarshalIndent(&cfg, "", "   ")
И потенциальная угроза. В реальных проектах так лучше не делать потому что секреты в конфиг чаще всего прокидываются для конкретного процесса и показывать их всем не правильно

2023-12-18 08:50 UTC, edylcrm approved these changes

2024-05-16 12:32 UTC, merged